--
-- SPDX-License-Identifier: BSD-2-Clause-FreeBSD
--
-- Copyright (c) 2026 The FreeCORE Project
--
-- FreeCORE boot art. Generated by freecore-brand/tools/build_boot_bundle.py
-- from ascii/brand-freecore.txt; regenerate there, do not hand-edit.
--

local drawer = require("drawer")

local freecore_brand = {
" _____               ____ ___  ____  _____",
"|  ___| __ ___  ___ / ___/ _ \\|  _ \\| ____|",
"| |_ | '__/ _ \\/ _ \\ |  | | | | |_) |  _|",
"|  _|| | |  __/  __/ |__| |_| |  _ <| |___",
"|_|  |_|  \\___|\\___|\\____\\___/|_| \\_\\_____|",
}

drawer.addBrand("FreeCORE", {
	requires_color = false,
	graphic = freecore_brand,
})

return true
