--
-- SPDX-License-Identifier: BSD-2-Clause-FreeBSD
--
-- Copyright (c) 2026 The FreeCORE Project
--
-- FreeCORE boot art. Generated by freecore-brand/tools/build_boot_bundle.py
-- from ascii/logo-freecore.txt; regenerate there, do not hand-edit.
--

local drawer = require("drawer")

local freecore_logo = {
"o------o-------x",
"       |",
"       |",
"       '-------#",
}

drawer.addLogo("FreeCORE", {
	requires_color = false,
	graphic = freecore_logo,
	shift = {x = 5, y = 6},
})

return true
