<%
	try:
		middleware.call_sync('wireguard.config_valid')
	except Exception:
		raise FileShouldNotExist()

	config = middleware.call_sync('wireguard.config')
	peers = middleware.call_sync('wireguard.peer.query', [['enabled', '=', True]])
%>\
[Interface]
Address = ${config['address']}/${config['netmask']}
ListenPort = ${config['listen_port']}
PrivateKey = ${config['private_key']}
% if config['mtu']:
MTU = ${config['mtu']}
% endif
% for peer in peers:

# ${peer['name']}
[Peer]
PublicKey = ${peer['public_key']}
AllowedIPs = ${', '.join(peer['allowed_ips'])}
% if peer['preshared_key']:
PresharedKey = ${peer['preshared_key']}
% endif
% if peer['keepalive']:
PersistentKeepalive = ${peer['keepalive']}
% endif
% endfor
